name: Tests and Coverage Check For Pull Requests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Store your Cloudflare API token in GitHub Secrets
        run: wrangler deploy