name: Tests and Coverage Check For Pull Requests

on:
  push:
    branches:
      - staging
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bun
        run: |
            curl -fsSL https://bun.sh/install | bash
            echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun installation
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install
      
      - name: Check coverage threshold
        run: bun run test

      - name: Install Wrangler CLI
        run: bun install -g wrangler

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Store your Cloudflare API token in GitHub Secrets
        run: wrangler deploy --env staging